# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 10:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190124_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAnkDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountNumber', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(14)])),
                ('AcoountType', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=100)),
                ('IFSCCode', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.User')),
            ],
        ),
    ]
